#include "wled.h"

/*
 * HomeWizard P1 usermod
 *
 * Polls a HomeWizard P1 meter (Wi-Fi P1 dongle) on the local network and
 * exposes the current grid power as a WLED effect ("Grid Flow"):
 *   - offtake / import  (active_power_w > 0): purple pulses flowing in one direction
 *   - injection / export (active_power_w < 0): green pulses flowing the other way
 *   - near zero: calm white breathing
 *
 * The P1 meter is found automatically via mDNS (service _hwenergy._tcp),
 * or a fixed IP/hostname can be set in Usermod Settings.
 *
 * Data source: HomeWizard local API v1, GET http://<host>/api/v1/data
 * ("Local API" must be enabled in the HomeWizard Energy app).
 * API reference: https://api-documentation.homewizard.com/docs/v1/
 *
 * Implementation notes:
 *  - The HTTP request is fully asynchronous (AsyncClient); TCP callbacks only
 *    append to a buffer and set flags, all parsing and WLED state changes
 *    happen in the usermod loop() on the main task. This keeps the LED
 *    pipeline running and avoids the watchdog resets a blocking HTTPClient
 *    in loop() would cause.
 *  - mDNS discovery (MDNS.queryService) blocks for a few seconds, so it only
 *    runs while no host is known, with a retry backoff.
 *
 * Async TCP handling pattern based on usermods/usermod_v2_HttpPullLightControl
 * (Roel Broersma), effect structure based on usermods/user_fx.
 */

// AI: below section was generated by an AI

// ---------------------------------------------------------------------------
// State shared between the usermod instance and the effect function.
// Written from the main loop only (parsing happens in loop(), not in TCP
// callbacks), read by the effect on the same task -> no locking needed.
// ---------------------------------------------------------------------------
static float p1PowerW       = 0.0f;   // latest active power, >0 import, <0 export
static float p1PowerSmoothW = 0.0f;   // low-pass filtered power driving the visuals
static float p1Presence     = 0.0f;   // 0..1, fades in/out as data becomes (in)valid
static bool  p1DataValid    = false;  // false until first fetch or when data is stale
static int   p1DeadbandW    = 50;     // |power| below this is treated as "neutral"
static int   p1FullScaleW   = 2500;   // |power| at which color/speed reach maximum

// Fixed identity colors (matching common energy-app conventions)
static const uint32_t P1_COLOR_IMPORT = RGBW32(160,   0, 255, 0); // purple
static const uint32_t P1_COLOR_EXPORT = RGBW32(  0, 255,  60, 0); // green
static const uint32_t P1_COLOR_IDLE   = RGBW32(255, 255, 255, 0); // white

// ---------------------------------------------------------------------------
// Effect: Grid Flow
//
// Sliders:
//   Speed     - scales the flow speed (on top of the power-based speed)
//   Pulses    - number of pulses travelling along the segment
//   Trail     - length of the fading tail behind each pulse head
// The flow direction is fixed by import/export; use the segment "reverse"
// option to flip it for your physical layout.
// ---------------------------------------------------------------------------
static void mode_grid_flow(void) {
  if (SEGLEN < 1) { SEGMENT.fill(SEGCOLOR(0)); return; }

  // All rendering is driven by the low-pass filtered power, so poll steps,
  // deadband crossings and import/export flips all animate smoothly.
  const float power = p1PowerSmoothW;
  const bool importing = power > 0.0f;

  // Normalize |power| to 0..1 between deadband and full scale
  float t = (fabsf(power) - (float)p1DeadbandW) / (float)max(1, p1FullScaleW - p1DeadbandW);
  t = constrain(t, 0.0f, 1.0f);

  // Pulses gradually emerge from the breathing over the first quarter of the
  // power range instead of snapping in at the deadband edge
  const float emerge = constrain(t * 4.0f, 0.0f, 1.0f);

  // Color fades white -> purple (import) / green (export) with power.
  // A direction flip passes through the deadband, i.e. through white.
  const uint32_t ident = importing ? P1_COLOR_IMPORT : P1_COLOR_EXPORT;
  const uint32_t baseColor = color_blend(P1_COLOR_IDLE, ident, (uint8_t)(t * 255.0f));

  // Breathing level: bright when data is valid, dim while waiting for data.
  // p1Presence fades between the two so data loss/recovery is not a hard cut.
  const uint8_t breath = sin8_t(strip.now >> 4);                // ~4 s cycle
  const int breatheValid   = 140 + (breath >> 2);
  const int breatheInvalid = 30 + (breath >> 3);
  const int idleLevel = breatheInvalid + (int)((breatheValid - breatheInvalid) * p1Presence);

  // Flow speed in pixels/second: 4..60 px/s scaled by power and the speed slider
  float pxPerSec = (4.0f + 56.0f * t) * ((float)(1 + SEGMENT.speed) / 128.0f);
  // Position offset in 8.8 fixed point pixels; import and export flow in
  // opposite directions so you can see at a glance which way energy "moves"
  uint32_t offset = (uint32_t)((strip.now * (uint32_t)(pxPerSec * 256.0f)) / 1000);

  // Pulse spacing from the density slider (more density = more pulses)
  unsigned numPulses = 1 + ((SEGLEN * (unsigned)SEGMENT.intensity) >> 11);  // 1 pulse per ~8px at max
  unsigned spacing   = max(6U, (unsigned)SEGLEN / numPulses);
  const uint32_t spacingFP = (uint32_t)spacing << 8;

  // Trail length: fraction of the spacing that fades out behind the head
  unsigned trail = 2 + (((unsigned)SEGMENT.custom1 * (spacing - 2)) >> 8);
  const uint32_t trailFP = (uint32_t)trail << 8;

  // Pulses get brighter with power
  const uint8_t pulseBri = 170 + (uint8_t)(85.0f * t);

  for (unsigned i = 0; i < SEGLEN; i++) {
    uint32_t posFP = ((uint32_t)i << 8);
    // Import flows toward segment start, export flows toward segment end
    posFP = importing ? (posFP + offset) : (posFP - offset);
    uint32_t phase = posFP % spacingFP;   // 0 = pulse head

    // Flow layer brightness: bright head fading along the trail, dim background
    int flowLevel;
    if (phase < trailFP) {
      flowLevel = 255 - (int)((phase * (255 - 40)) / trailFP);
      flowLevel = scale8((uint8_t)flowLevel, pulseBri);
    } else {
      flowLevel = 24;
    }

    // Cross-fade breathing -> flow by emerge for a seamless neutral boundary
    int level = idleLevel + (int)((flowLevel - idleLevel) * emerge);
    level = constrain(level, 10, 255);

    SEGMENT.setPixelColor(i, color_fade(baseColor, (uint8_t)level));
  }
}
static const char _data_FX_MODE_GRID_FLOW[] PROGMEM = "Grid Flow@Speed,Pulses,Trail;;;1;sx=128,ix=96,c1=128";

// ---------------------------------------------------------------------------
// Usermod
// ---------------------------------------------------------------------------
class HomeWizardP1Usermod : public Usermod {
private:
  static const char _name[];

  bool enabled = true;

  // Configuration (Usermod Settings)
  String host = "";                  // empty = discover via mDNS
  uint16_t updateIntervalMs = 3000;  // poll interval; P1 v1 data updates about once per second
  bool autoDiscover = true;

  // Discovery state
  String discoveredHost = "";
  unsigned long lastDiscoveryAttempt = 0;
  static const unsigned long DISCOVERY_RETRY_MS = 30000;

  // Fetch state
  AsyncClient *client = nullptr;
  unsigned long lastFetchStart = 0;
  unsigned long lastGoodData = 0;
  static const unsigned long FETCH_TIMEOUT_MS = 5000;   // watchdog for a hanging client
  static const unsigned long DATA_STALE_MS = 20000;     // invalidate power data after this

  // Response buffer, filled by TCP callbacks, parsed in loop().
  // 6 KiB fits headers + the v1 JSON payload comfortably.
  static const size_t RESP_BUF_SIZE = 6144;
  char  *respBuf = nullptr;
  volatile size_t respLen = 0;
  volatile bool respComplete = false;   // set by onDisconnect: response fully received
  volatile bool clientFailed = false;   // set by onError/onTimeout

  // Status for the info page
  bool lastFetchOk = false;
  String lastError = "";

  // Timestamp for the visual smoothing filter
  unsigned long lastSmoothUpdate = 0;

  bool haveHost() const { return host.length() > 0 || discoveredHost.length() > 0; }
  String activeHost() const { return host.length() > 0 ? host : discoveredHost; }

  // Discover the P1 meter via mDNS (_hwenergy._tcp). Blocking for a few
  // seconds, so this is only called while no host is known, with backoff.
  void discoverMeter() {
#ifdef ARDUINO_ARCH_ESP32
    lastDiscoveryAttempt = millis();
    DEBUG_PRINTLN(F("P1: mDNS discovery (_hwenergy._tcp)..."));
    int n = MDNS.queryService("hwenergy", "tcp");
    for (int i = 0; i < n; i++) {
      String productType = MDNS.txt(i, "product_type");
      DEBUG_PRINTF_P(PSTR("P1: mDNS result %d: %s (%s)\n"), i, MDNS.IP(i).toString().c_str(), productType.c_str());
      // HWE-P1 is the P1 meter; other HomeWizard products (kWh meter, socket) also announce hwenergy
      if (productType.startsWith(F("HWE-P1")) || n == 1) {
        discoveredHost = MDNS.IP(i).toString();
        DEBUG_PRINTF_P(PSTR("P1: using meter at %s\n"), discoveredHost.c_str());
        return;
      }
    }
    if (n > 0 && discoveredHost.length() == 0) {
      // No explicit P1 found, fall back to the first announced device
      discoveredHost = MDNS.IP(0).toString();
    }
    if (discoveredHost.length() == 0) DEBUG_PRINTLN(F("P1: no meter found via mDNS"));
#else
    // ESP8266: no service discovery implemented, a manual host is required
    lastDiscoveryAttempt = millis();
#endif
  }

  // Kick off an asynchronous GET /api/v1/data. Returns immediately; the
  // response is collected by the TCP callbacks and parsed later in loop().
  void startFetch() {
    if (client != nullptr) return;   // previous request still in flight

    respLen = 0;
    respComplete = false;
    clientFailed = false;

    client = new AsyncClient();
    if (!client) { lastError = F("out of memory"); return; }

    client->onData([](void *arg, AsyncClient *c, void *data, size_t len) {
      // Runs on the async_tcp task: only append to the buffer, no WLED calls here
      HomeWizardP1Usermod *um = (HomeWizardP1Usermod*)arg;
      size_t space = RESP_BUF_SIZE - 1 - um->respLen;
      size_t toCopy = len < space ? len : space;
      if (toCopy > 0) {
        memcpy(um->respBuf + um->respLen, data, toCopy);
        um->respLen = um->respLen + toCopy;
        um->respBuf[um->respLen] = '\0';
      }
    }, this);

    client->onDisconnect([](void *arg, AsyncClient *c) {
      // Server closed the connection (Connection: close) -> response complete.
      // Deleting the client here follows the AsyncTCP reference pattern.
      HomeWizardP1Usermod *um = (HomeWizardP1Usermod*)arg;
      if (um->client == c) {
        um->client = nullptr;
        um->respComplete = true;
      }
      delete c;
    }, this);

    client->onTimeout([](void *arg, AsyncClient *c, uint32_t time) {
      // Only flag the failure; do NOT delete here. Deleting runs ~AsyncClient,
      // whose close fires the onDisconnect callback, which would delete again.
      // The rx timeout closes the connection shortly after, and onDisconnect
      // performs the (single) delete.
      HomeWizardP1Usermod *um = (HomeWizardP1Usermod*)arg;
      if (um->client == c) {
        um->client = nullptr;
        um->clientFailed = true;
      }
    }, this);

    client->onError([](void *arg, AsyncClient *c, int8_t error) {
      HomeWizardP1Usermod *um = (HomeWizardP1Usermod*)arg;
      if (um->client == c) {
        um->client = nullptr;
        um->clientFailed = true;
      }
      // AsyncTCP deletes a client that failed to connect on its own; do not delete here
    }, this);

    client->onConnect([](void *arg, AsyncClient *c) {
      HomeWizardP1Usermod *um = (HomeWizardP1Usermod*)arg;
      String req = String(F("GET /api/v1/data HTTP/1.1\r\nHost: ")) + um->activeHost() +
                   F("\r\nConnection: close\r\nAccept: application/json\r\n\r\n");
      c->write(req.c_str());
    }, this);

    client->setRxTimeout(4);   // seconds
    client->setAckTimeout(4000);

    lastFetchStart = millis();
    if (!client->connect(activeHost().c_str(), 80)) {
      delete client;
      client = nullptr;
      clientFailed = true;
    }
  }

  // Parse the buffered HTTP response; runs on the main task.
  void parseResponse() {
    lastFetchOk = false;

    char *body = strstr(respBuf, "\r\n\r\n");
    if (!body) { lastError = F("no HTTP body"); return; }
    body += 4;

    // Basic status line check ("HTTP/1.1 200 OK")
    if (strncmp(respBuf, "HTTP/1.1 200", 12) != 0 && strncmp(respBuf, "HTTP/1.0 200", 12) != 0) {
      lastError = F("HTTP error");
      char *sp = strchr(respBuf, ' ');
      if (sp) lastError += String(sp).substring(0, 5);
      // A 404 here usually means the Local API is disabled in the HomeWizard app
      return;
    }

    // Only extract the fields we need; the filter keeps memory usage small
    StaticJsonDocument<64> filter;
    filter["active_power_w"] = true;
    StaticJsonDocument<256> doc;
    DeserializationError err = deserializeJson(doc, body, DeserializationOption::Filter(filter));
    if (err) { lastError = String(F("JSON: ")) + err.c_str(); return; }
    if (!doc.containsKey("active_power_w")) { lastError = F("no active_power_w"); return; }

    p1PowerW = doc["active_power_w"].as<float>();
    p1DataValid = true;
    lastGoodData = millis();
    lastFetchOk = true;
    lastError = "";
    DEBUG_PRINTF_P(PSTR("P1: %.0f W\n"), p1PowerW);
  }

public:
  void setup() override {
    respBuf = (char*)d_malloc(RESP_BUF_SIZE);
    strip.addEffect(255, &mode_grid_flow, _data_FX_MODE_GRID_FLOW);
  }

  void loop() override {
    if (!enabled || respBuf == nullptr) return;

    // Low-pass filter the power value (and a data-presence factor) toward
    // their targets with a ~1.2 s time constant. The effect renders from the
    // filtered values, so 3 s poll steps become smooth ramps instead of jumps.
    unsigned long now = millis();
    unsigned long dt = now - lastSmoothUpdate;
    if (dt > 0) {
      lastSmoothUpdate = now;
      if (dt > 1000) dt = 1000;  // avoid a huge first step after boot/reconnect
      float a = (float)dt / (1200.0f + (float)dt);
      float powerTarget = p1DataValid ? p1PowerW : 0.0f;  // fade home to neutral when data is lost
      p1PowerSmoothW += (powerTarget - p1PowerSmoothW) * a;
      float presenceTarget = p1DataValid ? 1.0f : 0.0f;
      p1Presence += (presenceTarget - p1Presence) * a;
    }

    // Handle a completed or failed request first (flags set by TCP callbacks)
    if (respComplete) {
      respComplete = false;
      parseResponse();
    }
    if (clientFailed) {
      clientFailed = false;
      lastFetchOk = false;
      if (lastError.length() == 0) lastError = F("connect failed");
      // If a manually configured host keeps failing, do not clear it;
      // a discovered host might be stale though, so forget it and rediscover
      if (host.length() == 0 && millis() - lastGoodData > DATA_STALE_MS) discoveredHost = "";
    }

    // Watchdog for a client that neither completes nor errors out
    if (client != nullptr && millis() - lastFetchStart > FETCH_TIMEOUT_MS) {
      AsyncClient *c = client;
      client = nullptr;    // detach first so callbacks from close() are ignored
      c->onDisconnect(nullptr);
      c->onError(nullptr);
      c->onTimeout(nullptr);
      c->onData(nullptr);
      delete c;
      lastFetchOk = false;
      lastError = F("timeout");
    }

    // Mark data stale when fetches keep failing, so the effect falls back to "waiting"
    if (p1DataValid && millis() - lastGoodData > DATA_STALE_MS) p1DataValid = false;

    if (!WLED_CONNECTED) return;

    // No host known: try mDNS discovery with backoff
    if (!haveHost()) {
      if (autoDiscover && (lastDiscoveryAttempt == 0 || millis() - lastDiscoveryAttempt > DISCOVERY_RETRY_MS)) {
        discoverMeter();
      }
      return;
    }

    // Time for the next poll?
    if (client == nullptr && millis() - lastFetchStart >= updateIntervalMs) {
      startFetch();
    }
  }

  void addToJsonInfo(JsonObject &root) override {
    JsonObject user = root["u"];
    if (user.isNull()) user = root.createNestedObject("u");
    JsonArray info = user.createNestedArray(FPSTR(_name));

    if (!enabled) { info.add(F("disabled")); return; }
    if (!haveHost()) {
      info.add(autoDiscover ? F("searching for P1 meter...") : F("no host configured"));
      return;
    }
    if (p1DataValid) {
      String s = String(p1PowerW, 0) + F(" W ");
      if (p1PowerW > p1DeadbandW)       s += F("(offtake)");
      else if (p1PowerW < -p1DeadbandW) s += F("(injection)");
      else                              s += F("(neutral)");
      s += F(" @ ");
      s += activeHost();
      info.add(s);
    } else {
      String s = String(F("no data from ")) + activeHost();
      if (lastError.length() > 0) s += String(F(" - ")) + lastError;
      info.add(s);
    }
  }

  void addToConfig(JsonObject &root) override {
    JsonObject top = root.createNestedObject(FPSTR(_name));
    top["enabled"] = enabled;
    top["host"] = host;
    top["autoDiscover"] = autoDiscover;
    top["updateIntervalMs"] = updateIntervalMs;
    top["deadbandW"] = p1DeadbandW;
    top["fullScaleW"] = p1FullScaleW;
  }

  bool readFromConfig(JsonObject &root) override {
    JsonObject top = root[FPSTR(_name)];
    bool configComplete = !top.isNull();

    String prevHost = host;
    configComplete &= getJsonValue(top["enabled"], enabled, enabled);
    configComplete &= getJsonValue(top["host"], host, host);
    configComplete &= getJsonValue(top["autoDiscover"], autoDiscover, autoDiscover);
    configComplete &= getJsonValue(top["updateIntervalMs"], updateIntervalMs, updateIntervalMs);
    configComplete &= getJsonValue(top["deadbandW"], p1DeadbandW, p1DeadbandW);
    configComplete &= getJsonValue(top["fullScaleW"], p1FullScaleW, p1FullScaleW);

    updateIntervalMs = max((uint16_t)1000, updateIntervalMs);
    p1DeadbandW = max(0, p1DeadbandW);
    p1FullScaleW = max(p1DeadbandW + 1, p1FullScaleW);
    host.trim();
    if (host != prevHost) discoveredHost = "";  // host changed: reset discovery state

    return configComplete;
  }
};

// AI: end

const char HomeWizardP1Usermod::_name[] PROGMEM = "HomeWizard P1";

static HomeWizardP1Usermod homewizard_p1;
REGISTER_USERMOD(homewizard_p1);
